name: openfold-env 
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python
  - libgcc
  - setuptools
  - pip
  - openmm
  - pdbfixer
  - pytorch-lightning
  - biopython
  - numpy
  - pandas
  - PyYAML
  - requests
  - scipy
  - tqdm
  - typing-extensions
  - wandb
  - modelcif
  - awscli
  - ml-collections
  - aria2
  - mkl
  - git
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2
  - bioconda::mmseqs2
  #- pytorch::pytorch
  - pip:
      - deepspeed
      - dm-tree
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/Dao-AILab/flash-attention.git@5b838a8
